### ISSUE TITLE
Add validation to ensure that "Short Route" has a leading "/"

### ISSUE THREAD

**Issue by webchick** [joellord/mdblinks#2]
I accidentally added a path without a leading "/" and when you do that, you not only create a broken link, but any subsequent links you create will have that broken route hard-coded and unchangeable until you shift+reload the form.

Some client-side validation here would be cool. 😎

**Comment by webchick** [comment]
Hm. Or alternately, just silently add it if it's not there so the user doesn't even need to think about it? 🤔

**Comment by joellord** [comment]
Agreed that simply adding it would make a better user experience. On the other, I wanted to test out how validation works in a modal so I fixed it :)

**Comment by joellord** [comment]
Fixed in bbc467944d14a8d42aadad1208bd1c8f30f1a78e
